function draw_axis_dyna(name, data1, data2, t)
Fig = figure(...
    'Units',           'pixels',...
    'Name',            name,...
    'NumberTitle',     'off',...
    'IntegerHandle',   'off');
% 创建axes对象, 设定坐标轴属性
AxesH = axes(...
    'Parent',  Fig,...
    'Xlim',    [0 60],...
    'XGrid',   'on',...
    'YGrid',   'on',...
    'Visible', 'on');


realtrace = line(AxesH, t, data1, 'linewidth',2);
precisetrace = line(AxesH, t, data2,...
                    'color','r',...
                    'linewidth',2);
bench = line(AxesH, [0 60], [9.79815 9.79815],...
                    'color','g',...
                    'linewidth',2,...
                    'linestyle','--');               
xlabel(AxesH, 't/min');
ylabel(AxesH, 'g/(m/s^2)');
legend(AxesH,[realtrace,precisetrace,bench],...
    'ESA(before processing)','Combine(after processing)','Benchmark Value',...
    'location','northwest');
% 指定保存路径和格式
saveas(Fig,['E:\E盘\论文相关\IEEE_Sensor_Journal\simu_code\simu\image\' Fig.Name],'pdf')
end